### ISSUE TITLE
Crash on currentView.rect!.width

### ISSUE THREAD

**Issue by aliakber945** [ocdrummer47/AutoLayoutMagic#10]
This line is causing crash when using storyboard to apply autolayouts
attributeData["multiplier"] = "(currentView.rect!.width)/(currentView.parentView!.rect!.width)"

Method Name:
 private func generateConstraints(currentView: View, constraintParentNode: NSXMLElement) 

it causes crash in both cases when using aspect ratio or not.

**Comment by akordadev** [comment]
I'm working on a fix for this.  It may be related to your width/height in your storyboard being a decimal like "38.5"

**Comment by akordadev** [comment]
Closing this issue.  Let me know if you still have problems after latest update :)
