### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [ocdrummer47/AutoLayoutMagic#11]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by ihmunro** [comment]
Same here

**Comment by akordadev** [comment]
There is currently a pull request that updates for Swift 3.  We will get this merged in ASAP!

**Comment by akordadev** [comment]
I have merged a swift 3 pull request in.  Let me know if there are any issues.  Closing
