### ISSUE TITLE
Make a beta release of app for swift 3.0 support

### ISSUE THREAD

**Issue by gauravds** [ocdrummer47/AutoLayoutMagic#15]
Please make a beta release of this app with swift 3.0 support like https://github.com/gauravds/AutoLayoutMagic/releases. You can pick up the[ build app from here](https://github.com/gauravds/AutoLayoutMagic/releases).

**People generally don't want to compile and build the tool and then use.**

Another good suggestion that in XCode 8 we could make an xcode plugin for adding constrain in storyboard. before XCode 8 there is Alcatraz but that is history, just we could make an xcode plugin and publish to app store. 

Looking forward to your reply.

**Comment by akordadev** [comment]
I will make 2 releases soon, one for swift 3, and another for swift 2.  

I would also like to look into building an xcode plugin, great suggestion!

**Comment by akordadev** [comment]
Closing this issue, and opening a new issue for a plugin
