### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [ocdrummer47/AutoLayoutMagic#9]
As I mentioned on [Awesome-iOS' #820 issue](https://github.com/vsouza/awesome-ios/pull/820), your project needs an improvement on the `README.md`.
The repo [On/Off Button](https://github.com/rakaramos/OnOffButton) had the same problem, so you can follow [their fix](https://github.com/rakaramos/OnOffButton/issues/1)  and see how to improve the README.md

Let me know if you need any help! 😃

**Comment by vsouza** [comment]
I have a fork of an awesome template of readme, check this:

https://github.com/vsouza/readme-template

**Comment by akordadev** [comment]
Thanks for the feedback guys.  On it!

**Comment by akordadev** [comment]
I have updated and improved the README.  What do you think?

**Comment by lfarah** [comment]
@akordadev it's awesome. Because of your project me and @vsouza decided to create an [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template)

**Comment by vsouza** [comment]
can we close?

**Comment by akordadev** [comment]
Yes, this project was added to Awesome-IOS repo, and README is up to standard.  Closing ticket.  Thanks for the assistance everyone!
